# Generated by Django 5.2.12 on 2026-03-19 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_quiz', to='quizzes.quizrequest'),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='unique_correct_option_per_question'),
        ),
        migrations.AddConstraint(
            model_name='quizrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'processing', 'completed', 'failed'])), name='quizrequest_status_check'),
        ),
        migrations.AddConstraint(
            model_name='quizrequest',
            constraint=models.CheckConstraint(condition=models.Q(('question_count__gte', 1), ('question_count__lte', 50)), name='quizrequest_question_count_check'),
        ),
    ]
