# Generated by Django 5.2.12 on 2026-03-19 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '__first__'),
        ('quizzes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='communities.community'),
        ),
        migrations.AddField(
            model_name='quizrequest',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_requests', to='communities.community'),
        ),
    ]
