# Generated by Django 5.2.12 on 2026-03-19 04:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_attempts', models.IntegerField(default=0)),
                ('avg_score_pct', models.FloatField(default=0.0)),
                ('avg_completion_secs', models.IntegerField(default=0)),
                ('question_stats', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
